INSERT INTO address (id, address, city, state) VALUES (1, 'Rua Bahia, 10', 'Curitiba', 'PR');
INSERT INTO address (id, address, city, state) VALUES (2, 'Rua Amazonas, 280', 'Campinas', 'SP');
INSERT INTO address (id, address, city, state) VALUES (3, 'Rua Castro Alves, 50', 'Valinhos', 'SP');
INSERT INTO address (id, address, city, state) VALUES (4, 'Rua Santa Rita, 147', 'Barbacena', 'MG');
INSERT INTO address (id, address, city, state) VALUES (5, 'Rua Boa Vista, 56', 'Ipatinga', 'MG');
INSERT INTO address (id, address, city, state) VALUES (6, 'Rua das Flores, 144', 'Londrina', 'PR');
INSERT INTO address (id, address, city, state) VALUES (7, 'Rua Pernambuco, 33', 'Cianorte', 'PR');
INSERT INTO address (id, address, city, state) VALUES (8, 'Rua 10, 66', 'Niterói', 'RJ');
INSERT INTO address (id, address, city, state) VALUES (9, 'Rua Santos Dumont, 1740', 'Parati', 'RJ');
INSERT INTO address (id, address, city, state) VALUES (10, 'Rua Tiradentes, 12', 'Joinville', 'SC');
INSERT INTO address (id, address, city, state) VALUES (11, 'Rua das Orquídeas, 77', 'Blumenau', 'SC');
INSERT INTO address (id, address, city, state) VALUES (12, 'Rua Treze, 1100', 'Florianópolis', 'SC');
INSERT INTO address (id, address, city, state) VALUES (13, 'Rua Portes, 345', 'Coxim', 'MS');
INSERT INTO address (id, address, city, state) VALUES (14, 'Avenida Brasil, 67', 'Dourados', 'MS');
INSERT INTO address (id, address, city, state) VALUES (15, 'Avenida da Saudade, 788', 'Bataguassu', 'MS');
